<?php
/**
 * Question create template
 *
 * @var QuestionEdit $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Tigren\Customer\Block\QuestionEdit;

?>

<div class="block">
    <div class="title">
        <strong><?= $block->escapeHtml(__('Tigren Customer Edit Form')) ?></strong>
    </div>
    <?php //$block->returnIdQuestion() ?>
    <div class="content">
        <form class="form question"
              action="<?php echo $block->geturl()
                  .'tigren_customer/question/edititem/?id='
                  .$block->returnIdQuestion() ?>" method="post">
            <div class="control">
                <div class="form-group">
                    <label for="question">
                        <?= $block->escapeHtml(__('Tittle')) ?>
                    </label>
                    <input type="text" name="title" class="form-control"
                           id="question"
                           placeholder=" <?= $block->escapeHtml(__('Tittle Content')) ?>">
                </div>

                <div class="form-group">
                    <label
                        for="content"> <?= $block->escapeHtml(__('Content')) ?>
                    </label>
                    <input type="text" name="content" class="form-control"
                           id="content"
                           placeholder=" <?= $block->escapeHtml(__('Question Content')) ?>">
                </div>

                <div class="form-group">
                    <label
                        for="author_id"> <?= $block->escapeHtml(__('Author ID')) ?></label>
                    <input type="text" name="author_id" class="form-control"
                           id="author_id"
                           placeholder=" <?= $block->escapeHtml(__('Author ID Content')) ?>">
                </div>
            </div>
            <br>
            <div class="actions">
                <button type="submit" class="btn btn-primary"
                        title="<?= $block->escapeHtml(__('Update')) ?>">
                    <span><?= $block->escapeHtml(__('Update')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
