<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * Question create template
 * @var Save $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Tigren\Customer\Block\Save;

?>

<div class="block">
    <div class="title">
        <strong><?= $block->escapeHtml(__('Tigren Question Form')) ?></strong>
    </div>
    <div class="content">
        <form class="form question"
              action="<?php
              if ($block->returnIdQuestion()) {
                  echo $block->getBaseUrl() . 'tigren_customer/question/save/?id=' . $block->returnIdQuestion();
              } else {
                  echo $block->getBaseUrl() . 'tigren_customer/question/save';
              }
              ?>"
              method="POST">
            <div class="control">
                <div class="form-group">
                    <label
                        for="question"> <?= $block->escapeHtml(__('Tittle')) ?></label>
                    <input type="text" name="title" class="form-control"
                           id="question"
                           value="<?php
                           if (!empty($block->getQuestionUpdate())) {
                               echo $block->getQuestionUpdate()->getTitle();
                           }
                           ?>" required>
                </div>
                <div class="form-group">
                    <label
                        for="content"> <?= $block->escapeHtml(__('Content')) ?></label>
                    <input type="text" name="content" class="form-control"
                           id="content"
                           value="<?php
                           if (!empty($block->getQuestionUpdate())) {
                               echo $block->getQuestionUpdate()->getContent();
                           }
                           ?>" required>
                </div>
            </div>
            <br>
            <div class="actions">
                <button type="submit" class="btn btn-primary"
                        title="<?= $block->escapeHtml(__('Save')) ?>"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Save')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>

