<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * Question create template
 * @var Save $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Tigren\AdvancedQuestion\Block\Save;

?>

<div class="block">
    <div class="title">
        <strong><?= $block->escapeHtml(__('Tigren Question Form')) ?></strong>
    </div>
    <div class="content">
        <div class="control">
            <div class="form-group">
                <label
                    for="title"> <?= $block->escapeHtml(__('Tittle')) ?></label>
                <input type="text" name="title" class="form-control" id="title"
                       value="<?php
                       if (!empty($block->getQuestionUpdate())) {
                           echo $block->getQuestionUpdate()->getTitle();
                       }
                       ?>">
            </div>
            <div class="form-group">
                <label
                    for="content"> <?= $block->escapeHtml(__('Content')) ?></label>
                <input type="text" name="content" class="form-control" id="content"
                       value="<?php
                       if (!empty($block->getQuestionUpdate())) {
                           echo $block->getQuestionUpdate()->getContent();
                       }
                       ?>">
            </div>

        </div>
        <br>
        <div class="actions">
            <button type="submit" class="btn btn-primary btnSave" id="btn_save"
                    title="<?= $block->escapeHtml(__('Save')) ?>"
                    data-idQuestion="<?php echo $block->returnIdQuestion() ?>">
                <?= $block->escapeHtml(__('Save')) ?>
            </button>
        </div>

    </div>
</div>
<script type="text/x-magento-init">
{
    "#btn_save": {
        "question_js": {}
    }
}

</script>
